//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub use super::conversations::Entity as Conversations;
pub use super::messages::Entity as Messages;
pub use super::models::Entity as Models;
pub use super::settings::Entity as Settings;
